language: tex
git:
  depth: 1
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq install -y --no-install-recommends texlive-latex-recommended texlive-latex-extra latex-cjk-chinese*
- wget -q $(curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep -aPo "(?<=\"browser_download_url\":\ \")\S+\.deb(?=\")")
- sudo tar xvzf pandoc-* --strip-components 1 -C /usr
script:
- ./build.sh
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: output
  on:
    branch: master
