language: tex
git:
  depth: 1
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-recommended
- wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-linux.tar.gz && sudo tar xvzf pandoc-2.5-linux.tar.gz --strip-components 1 -C /usr
script:
- ./build.sh
